import type { NextPage } from "next";
import { withUrqlClient } from "next-urql";
import Head from "next/head";
import { createUrqlClient } from "../utils/createUrqlClient";
import { NavBar } from "../components/NavBar";
import { usePostsQuery } from "../generated/graphql";
import { isServer } from "../utils/isServer";
import NextLink from "next/link";
import Post from "../components/Post";
import React from "react";
import Spinner from "../components/Spinner";

const Home: NextPage = () => {
  const [variables, setVariables] = React.useState({
    limit: 15,
    cursor: null as null | string,
  });
  const [{ data, fetching }] = usePostsQuery({
    variables,
  });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="m-auto w-1/2">
        {!data && fetching ? (
          <Spinner />
        ) : (
          data!.posts.posts.map((p) => {
            return <Post post={p} />;
          })
        )}
        {data && data.posts.hasMore ? (
          <div className="text-center my-2 text-xl">
            <button
              onClick={() => {
                setVariables({
                  limit: variables.limit,
                  cursor:
                    data.posts.posts[data.posts.posts.length - 1].createdAt,
                });
              }}
            >
              load more
            </button>
          </div>
        ) : null}
      </div>
    </div>
  );
};

export default withUrqlClient(createUrqlClient, { ssr: true })(Home);
