import type { NextPage } from "next";
import { withUrqlClient } from "next-urql";
import Head from "next/head";
import { createUrqlClient } from "../utils/createUrqlClient";
import { NavBar } from "../components/NavBar";
import { usePostsQuery } from "../generated/graphql";
import { isServer } from "../utils/isServer";

const Home: NextPage = () => {
  const [{ data }] = usePostsQuery();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div>Hello world</div>
      <br />
      {!data ? (
        <div>loading...</div>
      ) : (
        data.posts.map((p) => <div key={p.id}>{p.title}</div>)
      )}
    </div>
  );
};

export default withUrqlClient(createUrqlClient, { ssr: true })(Home);
